### ISSUE TITLE
Larger CSV file

### ISSUE THREAD

**Issue by ohhsodead** [khalidabuhakmeh/PropertyNameClassifier#1]
I saw your readme and saw you wanted a larger CSV file. I have one with well over a million rows if you want it, it's about ~3GB though 😂

**Comment by khalidabuhakmeh** [comment]
... you might need to link it :)

**Comment by ohhsodead** [comment]
@khalidabuhakmeh sure, does it matter what the the data contains?

**Comment by khalidabuhakmeh** [comment]
I guess the point of this model is to guess the type based on the name chosen, so...maybe? 🤷‍♂️ #yolo

**Comment by ohhsodead** [comment]
@khalidabuhakmeh

Ohh, my file contains data scraped from servers about files. Probably not much use to you then lol
